### PR TITLE
Update to 1.19.1 and improve some stuff

### PR DESCRIPTION
**Pull request by TauCubed**
Update to 1.19
Improve main thread performance by removing string hash & lookups for config values
Fix readme.txt console spam

### CODE REVIEW

**Comment by TauCubed** [comment]
No problem, I updated it for my personal server and thought I might as well share the changes with you, if it'd make your life any easier.

As far as the deepslate issue goes, perhaps a more agnostic way of patching that issue would be to inherit the type of the block around the ore. If it is stone, replace with stone, if it is deepslate replace with deepslate, if it's netherack... and so on.

Cheers and thanks for the Roadmap, looking forward to it.

**Comment by stonar96** [comment]
> As far as the deepslate issue goes, perhaps a more agnostic way of patching that issue would be to inherit the type of the block around the ore. If it is stone, replace with stone, if it is deepslate replace with deepslate, if it's netherack... and so on.

Unfortunately, this isn't as easy as it sounds because of how Anti-Xray works internally. The blocks that are being used as replacement must be added into the block palettes per chunk section way before the obfuscation algorithm hides the blocks. Even if we add both blocks to all palettes (which is most of the time unnecessary and even therefore inefficient), it would still require checks within hot code to figure out which type must be used as replacement as you said (that's even more inefficient).

A simple check whether or not the chunk section is below 0 is easy to implement and doesn't noticeable affect the performance. That's why it was implemented that way, not because we didn't have other ideas. Infact, your (and other similar) ideas have been discussed several times before.

**Comment by stonar96** [comment]
Update: My cleanup PR PaperMC/Paper/pull/8104 has been merged (see roadmap above). Note that this Paper PR includes changes that will probably break your current updated build of RayTraceAntiXray.

**Comment by TauCubed** [comment]
For anyone following this PR. My dev branch has preliminary support for [8014](https://github.com/PaperMC/Paper/pull/8104)
Still need to do some more testing.

**Comment by stonar96** [comment]
I've rebased and I'm currently working on it. In the meantime, please don't push to main.

**Comment by stonar96** [comment]
I've updated to 1.19.1 and I did some minor refactoring (e.g. renaming, revert import changes, rearrange code). I've also reverted the following things for the following reasons:
- .gitignore changes: This is something you should add to your own [global .gitignore file](https://gist.github.com/subfuzion/db7f57fff2fb6998a16c) or to your own [local .git/info/exclude file](https://riptutorial.com/git/example/8049/ignore-files-locally-without-committing-ignore-rules). I'm using the language specific templates provided by [github/gitignore](https://github.com/github/gitignore) and I only add project related stuff to it. I won't start collecting ignore files of various different IDEs here.
- `EventPriority`: `WorldInitEvent` isn't `Cancellable`, thus `EventPriority` doesn't matter here at all.
- Config changes: The default (and example) config isn't meant to be a final config for production. Every user has different requirements and should deal with it. I've also written [this gist](https://gist.github.com/stonar96/69ca0311392188b7ac2ece226286147f) with recommended settings. Note that `ancient_debris` sould be added (if at all) to a nether specific config. Also note that `ancient_debris` never generates naturally exposed to air, thus it probably doesn't make sense to trace it at all (normal `engine-mode: 1` is sufficient).

**Pull request merged**
