### PR TITLE
Update to 1.20.2

### LINKED ISSUE #16: 1.20.2 Support
Hey! I hope it is not difficult to add 1.20.2 support, I am surprised nobody opened an issue yet...

Thank you 🙏

### PR DESCRIPTION
**Pull request by DaJokni**
This pull request does nothing but what the title says, updates the plugin to version 1.20.2.

Resolves #16

### CODE REVIEW

**Comment by stonar96** [comment]
Thanks, I will probably come to it this week. I have pushed some stuff that I had already planned for a while. I'm now working on the Folia PR (rebase and small fixes, work in progress), then I will rebase your PR and merge it. The code looks good to me.

**Comment by SrBedrock** [comment]
@stonar96 any update?

**Comment by 347180440** [comment]
等更新+1

**Comment by Huge-mistake** [comment]
> Thanks, I will probably come to it this week. I have pushed some stuff that I had already planned for a while. I'm now working on the Folia PR (rebase and small fixes, work in progress), then I will rebase your PR and merge it. The code looks good to me.

Any progress? RayTraceAntiXray is very important for my server, because RayTraceAntiXray does not support 1.20.2, so my server version has been stuck in 1.20.1 and cannot be updated, and 1.20.3 will be released soon😭😭😭

**Pull request merged**
