### PR TITLE
Update to 1.21.3, use only-script Apache Maven Wrapper distribution type and update minor stuff

### PR DESCRIPTION
**Pull request by metabrixkt**
:hedgehog:

_(it works)_

### CODE REVIEW

**Comment by qualk** [comment]
might as well do 1.21.4 too

**Comment by metabrixkt** [comment]
> might as well do 1.21.4 too
@qualk I will create a PR for 1.21.4 when this one is merged. Also, builds for both 1.21.3 and 1.21.4 are available at my fork's releases page: https://github.com/metabrixkt/RayTraceAntiXray/releases

**Comment by qualk** [comment]
Thank you man 🙏

**Comment by stonar96** [comment]
Hi, thanks and sorry for the late update. I'll also update to 1.21.4 shortly.

**Pull request merged**
